# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce71ec106b4cfcbb44b5ae09bdb6c0e86e04d3e6e5f17d6b406da55a01152fbfdb8fd6b7750eec604fec9d44506204bd8303c3441a4402338926095885cd9f2c

test:
  secret_key_base: e4b3145eccd310fc6739917ffb798480f60b43689655d7d86fec43919e752b7bf9fd7ce3b48e6cd420b5215ed8e17cbcadf7e24cb66d76287df1815e1c732ceb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
